---
- name: Palo Alto API configuration pull   
  hosts: all
  connection: local
  tasks:   
    - name: make post request with api key
      uri:
        validate_certs: no
        url: "https://<ip_address>/api/?type=config&action=show&key={{ pa_api_key }}"
        return_content: yes
        method: POST
      register: result

    - name: copy content
      copy:
        content: "{{ result.content }}"
        dest: configs/{{ inventory_hostname }}.cfg

    - name: Push configs to repository
      shell: "{{ lookup('template', 'pa_git_push.j2') }}"
      args:
        executable: /bin/bash
      register: pa_git_push_result
...
