---    
- name: Archive configuration
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos  
  tasks:     
    - junos_facts:        
        gather_subset: config      
      register: facts    
    - copy: content="{{ facts.ansible_facts.ansible_net_config }}"
         dest="configs/{{ ansible_net_hostname }}.cfg"
    
    - name: Push configs to repo 
      shell: "{{ lookup('template', 'junos_git_push.j2') }}"
      args:
        executable: /bin/bash
      register: juniper-git-push_result
...