- name: Gather disk facts from virtual machine using name
  vmware_guest_disk_facts:
    hostname: "{{ vcenter.url }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password | trim }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    name: "{{ vcenter_name }}"
  delegate_to: localhost
  register: disk_facts

- debug: msg="{{ disk_facts }}"